### ISSUE TITLE
VarLight does not work, and when it is enabled certain chunks become completely unplayable

### ISSUE THREAD

**Issue by JerryTheSlime16** [flori-schwa/VarLightRewrite#11]
The chunks that are unplayable are in the area I most recently added lighting to. Please let me know any information you see. See attached console error.

```
27.01 22:49:15 [Server] INFO JerryTheSlime16 issued server command: /varlight
27.01 22:49:15 [Server] ERROR null
27.01 22:49:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'varlight' in plugin VarLight v1.12.8
27.01 22:49:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
27.01 22:49:15 [Server] INFO Caused by: java.lang.IllegalStateException: zip file closed
27.01 22:49:15 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
27.01 22:49:15 [Server] INFO at me.shawlaf.command.AbstractCommand.lambda$register$1(AbstractCommand.java:68) ~[?:?]
27.01 22:49:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-790]
27.01 22:49:15 [Server] INFO ... 19 more
```

**Comment by JerryTheSlime16** [comment]
This is still an issue. I believe it happens whenever the server crashes after varlight data has been modified.

**Comment by flori-schwa** [comment]
Does this still happen with the latest VarLight RC installed? (https://github.com/flori-schwa/VarLight/releases/tag/vl-2.0-rc2)

Mind that the RC is currently incompatible with paper, can you test on the same world on a normal spigot server?

**Comment by JerryTheSlime16** [comment]
We are on a Paper server, and I do not have a method to test the same world on a spigot server.
